---
title: "Untitled"
author: "Oliver"
date: "12/8/2020"
output:
  pdf_document: default 
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
# naive bayes
nb_accuracy <- 0.63
nb_lower <- 0.55
nb_upper <- 0.65
nb <- c("Naive Bayes", nb_accuracy, paste0("[", nb_lower, ", ", nb_upper, "]"))

# basic logistic regression 
blr_accuracy <- 0.62
blr_lower <- 0.57
blr_upper <- 0.67
blr <- c("Basic Logistic Regression", blr_accuracy, 
         paste0("[", blr_lower, ", ", blr_upper, "]"))

# lasso regression  
lasso_accuracy <- 0.69
lasso_lower <- 0.65
lasso_upper <- 0.74
lasso <- c("Lasso Regression", lasso_accuracy, 
         paste0("[", lasso_lower, ", ", lasso_upper, "]"))

# svm  
svm_accuracy <- 0.69
svm_lower <- 0.64
svm_upper <- 0.74
svm <- c("Support Vector Machine", svm_accuracy, 
         paste0("[", svm_lower, ", ", svm_upper, "]"))

# random forest  
rf_accuracy <- 0.71
rf_lower <- 0.66
rf_upper <- 0.75
rf <- c("Random Forest", rf_accuracy, 
         paste0("[", rf_lower, ", ", rf_upper, "]"))
 
df <- rbind(nb, blr, lasso, svm, rf)
colnames(df) <- c("Model", "Accuracy", "95% CI")

knitr::kable(df, row.names = FALSE, digits = 2, format = "latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = "striped") 
```

```{r}
# mlp 
mlp <- c("Multilayer Perceptron", 0.70, 
         paste0("[", 0.65, ", ", 0.75, "]"))

# rnn
rnn <- c("Recurrent Neural Network", 0.71, 
         paste0("[", 0.66, ", ", 0.76, "]"))
 
df <- rbind(mlp, rnn)
colnames(df) <- c("Model", "Accuracy", "95% CI")

knitr::kable(df, row.names = FALSE, digits = 2, format = "latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = "striped") 
```

